# Generated by Django 4.2.2 on 2023-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_id', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('reply', models.TextField()),
                ('is_view', models.PositiveBigIntegerField()),
                ('is_view_num', models.PositiveBigIntegerField()),
                ('send_time', models.TimeField()),
            ],
        ),
    ]
