# Generated by Django 4.2.2 on 2023-06-27 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_board_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_remove_review_write_date_remove_review_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
